base_path: /modules
base_url: 'https://api.crowdin.com'
preserve_hierarchy: true
files:
  - source: /BedrockLauncher.Core/Resources/lang/lang.default.xaml
    translation: /BedrockLauncher.Core/Resources/lang/lang.%locale%.xaml
